### ISSUE TITLE
Error, when I try create new "Entry"

### ISSUE THREAD

**Issue by ayewiee** [jeffreyrdcs/RDPass-GUI#1]
Here's text of error, maybe, it can help you:

 Traceback (most recent call last):
   File "C:\Users\Artem41k\Desktop\passw\RDPass-GUI\kivy_rdpass.py", line 136, in <module>
     RdpassApp().run()
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 248, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\core\window\__init__.py", line 1412, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\core\window\__init__.py", line 1428, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\screenmanager.py", line 1198, in on_touch_down
     return super(ScreenManager, self).on_touch_down(touch)
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\relativelayout.py", line 297, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\Users\Artem41k\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\Artem41k\Desktop\passw\RDPass-GUI\rdpass.kv", line 868, in <module>
     on_press:  root.confirmbutton_onpress()
   File "C:\Users\Artem41k\Desktop\passw\RDPass-GUI\screens\addentryscreen.py", line 96, in confirmbutton_onpress
     new_entry = CredEntry(title=self.ids.titl_simpfield.text,
   File "C:\Users\Artem41k\Desktop\passw\RDPass-GUI\RDutils\cred_entry.py", line 19, in __init__
     self.password = encrypt_pass(password.encode(), self.salt.encode())
 AttributeError: 'bytes' object has no attribute 'encode'

**Comment by jeffreyrdcs** [comment]
Thanks, this is useful.  Can you let me know the packages you are using with pip list?  

Judging from the last line "AttributeError: 'bytes' object has no attribute 'encode'",   I think you may be using the package "bcrypt" where the code requires "py-bcrypt".  The two packages have similar function and module name, but one give a byte output the other gives a string output, which causes the error. If this is true, to fix it you may have to uninstall bcrypt, then install py-bcrypt.

The package I used is listed in requirements.txt.  I just tried with a new virtual env with python 3.9 and I cannot reproduce the error you have.
